import Link from "next/link";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import { authOptions } from "../../../lib/auth";
import { appConfig } from "../../../lib/env";
import { PageContainer,Shell } from "../../../components/ui";

export const dynamic="force-dynamic";
export default async function KpiMonthIndex(){const session=await getServerSession(authOptions);if(!session?.user?.email||!session.user.isAdmin)redirect('/');const month=new Date().toISOString().slice(0,7);return <Shell email={session.user.email} isAdmin><PageContainer className="px-0"><div className="space-y-6"><section className="rounded-2xl border bg-white p-6 shadow-sm"><p className="text-sm font-semibold uppercase tracking-wide text-blue-700">Monthly KPI Engine v2</p><h2 className="mt-2 text-3xl font-bold">Auditable KPI & payout snapshots</h2><p className="mt-3 max-w-3xl text-slate-600">Work is reconciled by source item, scored at Member × Project × Month, then rolled up by target units. Missing evidence remains N/A and locked snapshots are immutable.</p><div className={`mt-4 inline-flex rounded-full px-3 py-1 text-sm font-semibold ${appConfig.kpiEngineV2Enabled?'bg-green-100 text-green-800':'bg-amber-100 text-amber-800'}`}>{appConfig.kpiEngineV2Enabled?'Staging writes enabled':'Read-only / feature flag off'}</div></section><section className="rounded-2xl border bg-white p-6 shadow-sm"><h3 className="text-lg font-semibold">Open a month</h3><form className="mt-4 flex flex-wrap gap-3" action="/admin/kpi-month"><input className="rounded-lg border px-3 py-2" type="month" name="month" defaultValue={month}/><button className="rounded-lg bg-slate-900 px-4 py-2 font-semibold text-white">Open</button><Link className="rounded-lg border px-4 py-2 font-semibold text-blue-700" href={`/admin/kpi-month/${month}`}>Current month</Link><Link className="rounded-lg border px-4 py-2 font-semibold text-blue-700" href="/admin/monthly-kpi-settings">Lifecycle settings</Link></form></section></div></PageContainer></Shell>}
