import Link from "next/link";
import { getServerSession } from "next-auth";
import { AdminDataControls } from "../../../components/admin-controls";
import { redirect } from "next/navigation";
import { authOptions } from "../../../lib/auth";
import { getDateRange, normalizeDateRangeKey } from "../../../lib/dates";
import { aggregateCompared, type ComparedUrlPerformance } from "../../../lib/growth";
import { getAdminDiagnostics, getAdminMemberRows, getDbPerformance } from "../../../lib/postgres";
import { DataTableContainer, DateRangePicker, fmtGrowth, fmtNum, fmtPct, fmtPos, fmtKpi, kpiTone, MetricCard, MetricSection, SectionGrid, Shell, StatusBadge, UrlTable, WarningList, type MetricTone } from "../../../components/ui";
import { formatSignedNumber, getGrowthClassName } from "../../../lib/format";
import { uiLabel, yesNo } from "../../../lib/ui-labels";

function group(rows: ComparedUrlPerformance[], key: keyof Pick<ComparedUrlPerformance, "member_name" | "project">) {
  return Object.entries(rows.reduce<Record<string, ComparedUrlPerformance[]>>((acc, row) => { (acc[String(row[key])] ??= []).push(row); return acc; }, {}));
}

function growthMetricTone(value: number | null): MetricTone {
  if (value === null || value === 0) return "growth-neutral";
  return value > 0 ? "growth-positive" : "growth-negative";
}

export default async function AdminDashboard({ searchParams }: { searchParams?: { range?: string; startDate?: string; endDate?: string; sort?: import("../../../components/ui").UrlSortKey; direction?: import("../../../components/ui").UrlSortDirection; refreshError?: string } }) {
  const session = await getServerSession(authOptions);
  if (!session?.user?.email ) redirect("/");
  if (!session.user.isAdmin) redirect("/dashboard");
  const rangeKey = normalizeDateRangeKey(searchParams?.range);
  const range = getDateRange({ range: rangeKey, startDate: searchParams?.startDate, endDate: searchParams?.endDate });
  const performance = await getDbPerformance(rangeKey, range);
  const summary = aggregateCompared(performance);
  const [members, diagnostics] = await Promise.all([getAdminMemberRows(rangeKey, range, performance), getAdminDiagnostics()]);
  const bestGrowth = [...performance].sort((a,b)=>b.click_delta-a.click_delta).slice(0,10);
  const declining = performance.filter(r=>r.status==="declining").sort((a,b)=>a.click_delta-b.click_delta).slice(0,10);
  const selectedRangeLabel = range.label;
  return <Shell email={session.user.email} isAdmin={session.user.isAdmin}><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-semibold">Hiệu suất thành viên trong đội</h2><p className="text-sm text-slate-500">{range.label}: {range.startDate} đến {range.endDate}, so với {performance[0]?.previousRange.startDate} đến {performance[0]?.previousRange.endDate}</p><p className="mt-1 text-sm text-slate-600">Lượt nhấp toàn đội {summary.click_delta >= 0 ? "tăng" : "giảm"} {fmtGrowth(summary.click_growth_pct)} so với kỳ trước. Có {summary.declining} URL đang suy giảm.</p></div><div className="flex items-center gap-3"><span className="text-xs text-slate-500">Bộ nhớ đệm Performance</span></div></div>{searchParams?.refreshError && <div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{searchParams.refreshError}</div>}<AdminDataControls range={rangeKey} startDate={searchParams?.startDate} endDate={searchParams?.endDate} /><DateRangePicker range={rangeKey} startDate={searchParams?.startDate} endDate={searchParams?.endDate} preserve={searchParams} /><WarningList warnings={[...performance.map((p) => p.warning), diagnostics.missingMemberEmail ? "Một số thành viên thiếu ánh xạ email. Hãy kiểm tra MEMBER_EMAIL_MAP." : undefined, diagnostics.missingGscProperty ? "Một số dự án thiếu ánh xạ GSC. Hãy kiểm tra PROJECT_GSC_MAP." : undefined, !diagnostics.contentWorkedAtColumnExists ? "Thiếu cột content_urls.content_worked_at. Hãy chạy migrations/20260708_content_urls_content_worked_at.sql trong Neon." : undefined, diagnostics.urlsMissingContentWorkedAt ? `${diagnostics.urlsMissingContentWorkedAt} URL đang hoạt động thiếu Ngày / Ngày thực hiện.` : undefined]} />
  <SectionGrid>
    <MetricSection title={`Hiệu suất đội SEO - ${selectedRangeLabel}`} description="Các chỉ số khối lượng trong khoảng đã chọn." tone="quantity" metrics={[{ label: "Tổng số URL", value: performance.length }, { label: "Lượt nhấp hiện tại", value: fmtNum(summary.clicks) }, { label: "Lượt nhấp kỳ trước", value: fmtNum(summary.previous_clicks) }, { label: "Chênh lệch lượt nhấp", value: formatSignedNumber(summary.click_delta), tone: growthMetricTone(summary.click_delta) }, { label: "Hiển thị hiện tại", value: fmtNum(summary.impressions) }, { label: "Hiển thị kỳ trước", value: fmtNum(summary.previous_impressions) }, { label: "Chênh lệch hiển thị", value: formatSignedNumber(summary.impression_delta), tone: growthMetricTone(summary.impression_delta) }, { label: "URL chưa có dữ liệu", value: summary.noData }]} />
    <MetricSection title="Tăng trưởng SEO Performance" description="Các chỉ số tăng trưởng và hiệu quả trong khoảng đã chọn." tone="quality" metrics={[{ label: "Tăng trưởng lượt nhấp %", value: fmtGrowth(summary.click_growth_pct), tone: growthMetricTone(summary.click_growth_pct) }, { label: "Tăng trưởng hiển thị %", value: fmtGrowth(summary.impression_growth_pct), tone: growthMetricTone(summary.impression_growth_pct) }, { label: "CTR", value: fmtPct(summary.ctr), tone: "growth-neutral" }, { label: "Vị trí trung bình", value: fmtPos(summary.position), tone: "growth-neutral" }, { label: "URL tăng trưởng", value: summary.growing, tone: "growth-positive" }, { label: "URL suy giảm", value: summary.declining, tone: summary.declining > 0 ? "growth-negative" : "growth-neutral" }]} />
  </SectionGrid>
  <Section title="Bảng tổng hợp thành viên" rows={group(performance, "member_name")} />
  <Diagnostics diagnostics={diagnostics} /><h3 className="mb-3 mt-8 text-xl font-semibold">Hiệu suất đội SEO</h3><SectionGrid><MemberIndexSection title={`Hiệu suất đội SEO - ${selectedRangeLabel}`} members={members} mode="quantity" /><MemberIndexSection title="Tăng trưởng SEO Performance" members={members} mode="quality" /></SectionGrid>
  <h3 className="mb-3 mt-8 text-xl font-semibold">URL tăng trưởng tốt nhất</h3><UrlTable rows={bestGrowth} sort={searchParams?.sort || "clicks"} preserve={searchParams} /><h3 className="mb-3 mt-8 text-xl font-semibold">URL đang suy giảm</h3><UrlTable rows={declining} sort={searchParams?.sort || "clicks"} preserve={searchParams} /></Shell>;
}
function Section({ title, rows }: { title: string; rows: [string, ComparedUrlPerformance[]][] }) { return <div className="mt-8"><h3 className="mb-3 text-xl font-semibold">{title}</h3><DataTableContainer><table className="w-full min-w-[900px] text-[13px] sm:text-sm"><thead className="bg-slate-100 text-left"><tr><th className="p-3">Tên</th><th>URL</th><th>Lượt nhấp</th><th>Lượt nhấp kỳ trước</th><th>Tăng trưởng lượt nhấp</th><th>Tăng trưởng hiển thị</th><th>Trạng thái</th></tr></thead><tbody>{rows.map(([name, list]) => { const m = aggregateCompared(list); const status = m.declining > m.growing ? "declining" : m.growing ? "growing" : "stable"; return <tr className="border-t" key={name}><td className="p-3">{name}</td><td>{list.length}</td><td>{fmtNum(m.clicks)}</td><td>{fmtNum(m.previous_clicks)}</td><td><span className={getGrowthClassName(m.click_growth_pct)}>{fmtGrowth(m.click_growth_pct)}</span></td><td><span className={getGrowthClassName(m.impression_growth_pct)}>{fmtGrowth(m.impression_growth_pct)}</span></td><td><StatusBadge status={status}/></td></tr>; })}</tbody></table></DataTableContainer></div>; }

function Diagnostics({ diagnostics }: { diagnostics: Awaited<ReturnType<typeof getAdminDiagnostics>> }) {
  return <div className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><h3 className="mb-3 text-lg font-semibold">Chẩn đoán quản trị</h3><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><MetricCard label="URL đang hoạt động" value={diagnostics.activeUrls} /><MetricCard label="URL thiếu member_email" value={diagnostics.missingMemberEmail} /><MetricCard label="URL thiếu gsc_property" value={diagnostics.missingGscProperty} /><MetricCard label="Có cột content_worked_at" value={yesNo(diagnostics.contentWorkedAtColumnExists)} /><MetricCard label="URL thiếu content_worked_at" value={diagnostics.urlsMissingContentWorkedAt} /></div><div className="mt-4 grid gap-4 text-sm md:grid-cols-2"><div><div className="font-medium">Trạng thái sync_runs gần nhất</div><div className="text-slate-600">{diagnostics.latestSyncRun ? `${uiLabel(diagnostics.latestSyncRun.status)} (${String(diagnostics.latestSyncRun.created_at).slice(0,19)})` : "Chưa có lần đồng bộ nào"}</div></div><div><div className="font-medium">Trạng thái refresh_runs gần nhất</div><div className="text-slate-600">{diagnostics.latestRefreshRun ? `${uiLabel(diagnostics.latestRefreshRun.status)} (${String(diagnostics.latestRefreshRun.updated_at ?? diagnostics.latestRefreshRun.created_at).slice(0,19)})${diagnostics.latestRefreshRun.error_message ? ` — ${diagnostics.latestRefreshRun.error_message}` : ""}` : "Chưa có lần làm mới nào"}</div></div></div>{diagnostics.missingGscProjects.length > 0 && <p className="mt-3 text-sm text-amber-800">Dự án thiếu ánh xạ GSC: {diagnostics.missingGscProjects.join(", ")}</p>}</div>;
}

function MemberIndexSection({ title, members, mode }: { title: string; members: Awaited<ReturnType<typeof getAdminMemberRows>>; mode: "quantity" | "quality" }) {
  const sorted = [...members].sort((a, b) => { const av = a.finalPerformance?.performance_final_pct; const bv = b.finalPerformance?.performance_final_pct; if (av == null && bv == null) return mode === "quantity" ? b.quantityIndex - a.quantityIndex : b.qualityIndex - a.qualityIndex; if (av == null) return 1; if (bv == null) return -1; return bv - av; });
  const sectionTone = mode === "quantity" ? "border-blue-100 bg-blue-50/60" : "border-slate-200 bg-white";
  const headingTone = mode === "quantity" ? "bg-blue-50 text-blue-950" : "bg-slate-50 text-slate-950";
  return <DataTableContainer><div className={`${sectionTone}`}><h4 className={`border-b p-3 font-semibold ${headingTone}`}>{title}</h4><table className="w-full text-sm"><thead className="bg-slate-100 text-left"><tr><th className="p-3">Thành viên</th><th>{mode === "quantity" ? "Chỉ số số lượng" : "Chỉ số chất lượng"}</th><th>Performance cuối cùng %</th><th>Độ phủ</th><th>URL</th><th>Tăng trưởng</th><th>Trạng thái</th><th>{mode === "quantity" ? "Tín hiệu hỗ trợ" : "Sức khỏe danh mục"}</th></tr></thead><tbody>{sorted.map(m=><tr className="border-t" key={m.member_name}><td className="p-3"><Link className="text-blue-700" href={`/member-insights?member=${encodeURIComponent(m.member_name)}`}>{m.member_name}</Link></td><td className={mode === "quantity" ? "font-semibold text-blue-950" : undefined}>{mode === "quantity" ? m.quantityIndex : m.qualityIndex}</td><td><span className={`inline-flex rounded-full px-3 py-1 text-sm font-bold ${kpiTone(m.finalPerformance?.performance_final_pct) === "kpi-null" ? "bg-slate-100 text-slate-600" : kpiTone(m.finalPerformance?.performance_final_pct) === "kpi-risk" ? "bg-red-100 text-red-800" : kpiTone(m.finalPerformance?.performance_final_pct) === "kpi-support" ? "bg-orange-100 text-orange-800" : kpiTone(m.finalPerformance?.performance_final_pct) === "kpi-monitor" ? "bg-yellow-100 text-yellow-800" : kpiTone(m.finalPerformance?.performance_final_pct) === "kpi-good" ? "bg-blue-100 text-blue-800" : "bg-green-100 text-green-800"}`}>{fmtKpi(m.finalPerformance?.performance_final_pct)}</span></td><td>{m.finalPerformance ? fmtPct(m.finalPerformance.performance_final_coverage) : "—"}</td><td>{m.urlCount}</td><td><span className={getGrowthClassName(m.click_growth_pct)}>{fmtGrowth(m.click_growth_pct)}</span></td><td>{uiLabel(m.finalPerformance?.performance_final_status || m.snapshotStatus)}</td><td>{mode === "quantity" ? m.supportSignal : m.portfolioHealth}</td></tr>)}{sorted.length === 0 && <tr><td className="p-3 text-slate-500" colSpan={8}>Không tìm thấy URL nội dung đang hoạt động.</td></tr>}</tbody></table></div></DataTableContainer>;
}
