import assert from "node:assert/strict";
import test from "node:test";
import { reconcileWorkSourceRows } from "./work-source.ts";
import { resolveUnitRule } from "../kpi/unit-rule-resolver.ts";
import { calculateQuantity } from "../kpi/quantity.ts";
import { calculateMonthlyQuality } from "../kpi/quality.ts";
import { newContentRubricV2 } from "../kpi/rubrics.ts";
import { calculateSeoContent } from "../kpi/seo-content.ts";
import { scoreGrowthProject } from "../performance/strategies/growth-project.ts";
import { calculateFinalMonthlyKpi } from "../kpi/monthly-final.ts";
import { scoreBase } from "../kpi/types.ts";

test("fixture workflow reconciles source through final auditable payout",()=>{const raw=Array.from({length:14},(_,index)=>({source:"slack_list_sheet",sourceRowNumber:index+2,sourceItemId:`S${index}`,projectRaw:index%2?"PrintYourWear":"Print Your Wear",memberRaw:"Lan",workTypeRaw:"New Content",sourceStatusRaw:"Completed",urlRaw:`https://example.com/post-${index}?utm_source=slack`,workDateRaw:`2026-07-${String(index+1).padStart(2,"0")}`}));raw.push({...raw[0],sourceRowNumber:99,urlRaw:"https://app.bloggle.app/editor/1",sourceStatusRaw:"Review"});const reconciled=reconcileWorkSourceRows(raw);assert.equal(reconciled.canonicalRows.length,14);assert.equal(reconciled.duplicateRows.length,1);const events=reconciled.canonicalRows.map((row)=>({id:row.sourceItemId,unitValue:resolveUnitRule({project:row.project,memberName:row.member,workType:row.workType}).unitValue,status:row.status,isCountable:row.isCountable}));const quantity=calculateQuantity({events,targetUnits:14,month:"2026-07"});const criteria=newContentRubricV2.criteria.map((criterion)=>({criterionKey:criterion.key,score:4,note:"Reviewer evidence"}));const quality=calculateMonthlyQuality({month:"2026-07",eligibleEvents:events.map((event)=>({id:event.id,unitValue:event.unitValue})),reviews:events.map((event)=>({eventId:event.id,unitValue:event.unitValue,rubric:newContentRubricV2,criteria,status:"approved"}))});const content=calculateSeoContent(quantity,quality);const performance=scoreGrowthProject({metrics:events.slice(0,5).map((event,index)=>({eventId:event.id,unitValue:1,status:"observed",comparisonObserved:true,preClicks:10,postClicks:12+index,preImpressions:100,postImpressions:120+index*5})),thresholds:{minEligibleEvents:5,minDataCoveragePct:80,minTotalImpressions:500,zeroSignalScorePct:0,newSignalScorePct:60},project:"Print Your Wear",memberName:"Lan",month:"2026-07",dataAsOf:"2026-08-31"});const manual=(value)=>scoreBase({ruleVersion:"manual_v2",state:"approved",rawPct:value,payablePct:value,coveragePct:100});const final=calculateFinalMonthlyKpi({components:[{key:"discipline",weightPct:10,required:true,score:manual(90)},{key:"seo_content",weightPct:50,required:true,score:content},{key:"seo_performance",weightPct:20,required:false,score:performance},{key:"social_video",weightPct:20,required:true,score:manual(85)}]});assert.equal(final.state,"scored");assert.equal(final.coveragePct,100);assert.ok(final.payablePct>0&&final.payablePct<=100);assert.ok(final.payoutVnd>0);assert.equal(final.ruleVersion,"monthly_final_v2");});
