import assert from "node:assert/strict";
import test from "node:test";
import { classifyExactPageResult,calculateDataCoverage } from "../performance/data-status.ts";
import { completeDataCutoff } from "../performance/gsc-daily.ts";
import { buildEventWindows,buildFallbackEventWindows,laterEventContaminates } from "../performance/windows.ts";
import { scoreGrowthProject } from "../performance/strategies/growth-project.ts";
import { scoreNewGrowthProject } from "../performance/strategies/new-project.ts";
import { scoreStableAuditProject } from "../performance/strategies/stable-audit.ts";
import { observedZeroScore } from "../performance/strategies/common.ts";

const thresholds={minEligibleEvents:5,minDataCoveragePct:80,minTotalImpressions:100,zeroSignalScorePct:0,newSignalScorePct:60};
const metric=(id,overrides={})=>({eventId:String(id),unitValue:1,status:"observed",comparisonObserved:true,preClicks:10,postClicks:12,preImpressions:100,postImpressions:120,...overrides});
test("GSC observed zero is distinct from unknown",()=>{assert.equal(classifyExactPageResult({bulkObserved:false,exactQuerySucceeded:true,exactRowFound:false}),"observed_zero");assert.equal(classifyExactPageResult({bulkObserved:false,exactQuerySucceeded:false,exactRowFound:false,fetchError:true}),"unknown");const coverage=calculateDataCoverage([{status:"observed"},{status:"observed_zero"},{status:"unknown"}]);assert.ok(Math.abs(coverage.coveragePct-200/3)<1e-9);assert.ok(Math.abs(coverage.comparisonCoveragePct-200/3)<1e-9);assert.equal(coverage.known,2);assert.equal(coverage.unknown,1);});
test("complete cutoff excludes newest three days",()=>{assert.equal(completeDataCutoff("2026-07-31",new Date("2026-07-14T10:00:00Z")),"2026-07-11");assert.equal(completeDataCutoff("2026-06-30",new Date("2026-07-14T10:00:00Z")),"2026-06-30");});
test("event-relative windows and contamination are deterministic",()=>{const windows=buildEventWindows("2026-07-10",28,28,28,"2026-09-30");assert.deepEqual(windows.pre,{startDate:"2026-06-12",endDate:"2026-07-09",days:28});assert.deepEqual(windows.post,{startDate:"2026-08-08",endDate:"2026-09-04",days:28});assert.equal(laterEventContaminates("2026-07-10","2026-08-20",windows.post),true);});
test("fallback windows select the longest completed 28 then 14 then 7 day horizon",()=>{assert.equal(buildFallbackEventWindows({workDate:"2026-07-01",dataCutoff:"2026-08-20",seoLagDays:28}).effectiveWindowDays,14);assert.equal(buildFallbackEventWindows({workDate:"2026-07-01",dataCutoff:"2026-08-08",seoLagDays:28}).effectiveWindowDays,7);assert.equal(buildFallbackEventWindows({workDate:"2026-07-01",dataCutoff:"2026-07-31",seoLagDays:28,allowProvisional:true}).fallbackLevel,"provisional");});
test("new growth scores full fallback provisional observed-zero and unknown without auto-zero",()=>{
  const base={thresholds:{...thresholds,minEligibleEvents:1,minDataCoveragePct:60,minTotalImpressions:0,neutralScorePct:70},project:"P",memberName:"Lan",month:"2026-07",dataAsOf:"2026-07-31"};
  const full=scoreNewGrowthProject({...base,metrics:[metric(1,{effectiveWindowDays:28,ageDays:35})]});assert.equal(full.state,"scored");assert.notEqual(full.payablePct,null);
  const fallback=scoreNewGrowthProject({...base,metrics:[metric(1,{effectiveWindowDays:14,ageDays:20})]});assert.equal(fallback.state,"fallback_scored");
  const provisional=scoreNewGrowthProject({...base,metrics:[metric(1,{effectiveWindowDays:4,ageDays:4})]});assert.equal(provisional.state,"provisional");
  const zero=scoreNewGrowthProject({...base,metrics:[metric(1,{status:"observed_zero",preClicks:0,postClicks:0,preImpressions:0,postImpressions:0,effectiveWindowDays:14,ageDays:20})]});assert.ok(zero.payablePct>0);
  const unknown=scoreNewGrowthProject({...base,metrics:[metric(1,{status:"unknown",effectiveWindowDays:14})]});assert.equal(unknown.state,"provisional");assert.equal(unknown.payablePct,70);
});
test("observed-zero policy is age-banded and auditable",()=>{const policy={under_14_days:70,days_14_to_27:45,days_28_plus:10};assert.equal(observedZeroScore({ageDays:13},policy,0),70);assert.equal(observedZeroScore({ageDays:14},policy,0),45);assert.equal(observedZeroScore({ageDays:27},policy,0),45);assert.equal(observedZeroScore({ageDays:28},policy,0),10);assert.equal(observedZeroScore({ageDays:60},undefined,7),7);});
test("growth performance gates unreliable data and never auto-floors",()=>{const insufficient=scoreGrowthProject({metrics:[metric(1,{status:"unknown"})],thresholds,project:"P",memberName:"Lan",month:"2026-07",dataAsOf:"2026-07-11"});assert.equal(insufficient.payablePct,null);assert.equal(insufficient.state,"insufficient_data");const zero=scoreGrowthProject({metrics:Array.from({length:5},(_,i)=>metric(i,{status:"observed_zero",preClicks:0,postClicks:0,preImpressions:0,postImpressions:0})),thresholds:{...thresholds,minTotalImpressions:0},project:"P",memberName:"Lan",month:"2026-07",dataAsOf:"2026-07-11"});assert.equal(zero.payablePct,0);});
test("stable audit excludes partial contamination and only requires PM review for a majority",()=>{const partial=scoreStableAuditProject({metrics:[metric(1,{contaminated:true}),...Array.from({length:4},(_,i)=>metric(i+2))],thresholds:{...thresholds,minEligibleEvents:4},project:"P",memberName:"Lan",month:"2026-07",dataAsOf:"2026-09-30"});assert.notEqual(partial.state,"pm_review_required");const majority=scoreStableAuditProject({metrics:[metric(1,{contaminated:true}),metric(2,{contaminated:true}),metric(3)],thresholds,project:"P",memberName:"Lan",month:"2026-07",dataAsOf:"2026-09-30"});assert.equal(majority.state,"pm_review_required");assert.equal(majority.payablePct,null);});
