import assert from "node:assert/strict";
import test from "node:test";
import { classifyExactPageResult,calculateDataCoverage } from "../performance/data-status.ts";
import { completeDataCutoff } from "../performance/gsc-daily.ts";
import { buildEventWindows,laterEventContaminates } from "../performance/windows.ts";
import { scoreGrowthProject } from "../performance/strategies/growth-project.ts";
import { scoreNewProjectReadiness } from "../performance/strategies/new-project.ts";
import { scoreStableAuditProject } from "../performance/strategies/stable-audit.ts";

const thresholds={minEligibleEvents:5,minDataCoveragePct:80,minTotalImpressions:100,zeroSignalScorePct:0,newSignalScorePct:60};
const metric=(id,overrides={})=>({eventId:String(id),unitValue:1,status:"observed",comparisonObserved:true,preClicks:10,postClicks:12,preImpressions:100,postImpressions:120,...overrides});
test("GSC observed zero is distinct from unknown",()=>{assert.equal(classifyExactPageResult({bulkObserved:false,exactQuerySucceeded:true,exactRowFound:false}),"observed_zero");assert.equal(classifyExactPageResult({bulkObserved:false,exactQuerySucceeded:false,exactRowFound:false,fetchError:true}),"unknown");const coverage=calculateDataCoverage([{status:"observed"},{status:"observed_zero"},{status:"unknown"}]);assert.ok(Math.abs(coverage.coveragePct-200/3)<1e-9);assert.ok(Math.abs(coverage.comparisonCoveragePct-200/3)<1e-9);assert.equal(coverage.known,2);assert.equal(coverage.unknown,1);});
test("complete cutoff excludes newest three days",()=>{assert.equal(completeDataCutoff("2026-07-31",new Date("2026-07-14T10:00:00Z")),"2026-07-11");assert.equal(completeDataCutoff("2026-06-30",new Date("2026-07-14T10:00:00Z")),"2026-06-30");});
test("event-relative windows and contamination are deterministic",()=>{const windows=buildEventWindows("2026-07-10",28,28,28,"2026-09-30");assert.deepEqual(windows.pre,{startDate:"2026-06-12",endDate:"2026-07-09",days:28});assert.deepEqual(windows.post,{startDate:"2026-08-08",endDate:"2026-09-04",days:28});assert.equal(laterEventContaminates("2026-07-10","2026-08-20",windows.post),true);});
test("new project is payroll N/A without a floor",()=>{const result=scoreNewProjectReadiness({projectAgeDays:30,matureEligibleUrls:2,coveragePct:100,completeComparableWindows:0,totalImpressions:50,adminPromoted:false,dataAsOf:"2026-07-11"});assert.equal(result.payablePct,null);assert.equal(result.state,"not_applicable");});
test("growth performance gates unreliable data and never auto-floors",()=>{const insufficient=scoreGrowthProject({metrics:[metric(1,{status:"unknown"})],thresholds,project:"P",memberName:"Lan",month:"2026-07",dataAsOf:"2026-07-11"});assert.equal(insufficient.payablePct,null);assert.equal(insufficient.state,"insufficient_data");const zero=scoreGrowthProject({metrics:Array.from({length:5},(_,i)=>metric(i,{status:"observed_zero",preClicks:0,postClicks:0,preImpressions:0,postImpressions:0})),thresholds:{...thresholds,minTotalImpressions:0},project:"P",memberName:"Lan",month:"2026-07",dataAsOf:"2026-07-11"});assert.equal(zero.payablePct,0);});
test("stable audit contamination requires PM review",()=>{const result=scoreStableAuditProject({metrics:[metric(1,{contaminated:true}),...Array.from({length:4},(_,i)=>metric(i+2))],thresholds,project:"P",memberName:"Lan",month:"2026-07",dataAsOf:"2026-09-30"});assert.equal(result.state,"pm_review_required");assert.equal(result.payablePct,null);});
