import assert from "node:assert/strict";
import test from "node:test";
import { normalizeCanonicalUrl, parseSourceDate } from "./normalization.ts";
import { reconcileWorkSourceRows } from "./work-source.ts";
import { parseLegacyContentSheet } from "../sync/legacy-content-sheet.ts";
import { parseSlackListSheet } from "../sync/slack-list-sheet.ts";

test("headerless legacy sheet keeps its first data row",()=>{const rows=parseLegacyContentSheet([["Print Your Wear","https://example.com/first","Lan","7/1/2026","New Content"],["Print Your Wear","https://example.com/second","Lan","7/2/2026","Audit"]]);assert.equal(rows.length,2);assert.equal(rows[0].url,"https://example.com/first");assert.equal(rows[0].source_row_number,1);});
test("header-present legacy sheet maps columns by name",()=>{const rows=parseLegacyContentSheet([["URL","Member","Project","Type","Date"],["https://example.com/a","Lan","Print Your Wear","Audit","2026-07-03"]]);assert.equal(rows[0].project,"Print Your Wear");assert.equal(rows[0].content_type,"audit");});
test("URL normalization removes tracking and rejects admin URLs as public",()=>{const publicUrl=normalizeCanonicalUrl("http://WWW.Example.com/a/?utm_source=x#top");assert.equal(publicUrl.canonicalUrl,"https://example.com/a");assert.equal(publicUrl.isPublic,true);assert.equal(normalizeCanonicalUrl("https://example.com/wp-admin/post.php?post=1").isDraftOrAdmin,true);});
test("URL normalization joins GSC variants across protocol, www, slash, and tracking",()=>{const variants=["http://www.example.com/post/","https://example.com/post?utm_source=gsc#x","https://EXAMPLE.com//post"];assert.deepEqual(variants.map((value)=>normalizeCanonicalUrl(value).canonicalUrl),["https://example.com/post","https://example.com/post","https://example.com/post"]);});
test("slash dates are parsed as Vietnamese dd/MM/yyyy without timezone drift",()=>{assert.equal(parseSourceDate("07/01/2026"),"2026-01-07");assert.equal(parseSourceDate("31/07/2026"),"2026-07-31");assert.equal(parseSourceDate("2026-07-31T23:30:00+07:00"),"2026-07-31");});
test("missing project settings and domain conflicts remain content-countable diagnostics",()=>{const base={source:"content_urls_sheet",sourceRowNumber:2,sourceItemId:"C1",projectRaw:"Print Your Wear",memberRaw:"Lan",workTypeRaw:"New Content",sourceStatusRaw:"Completed",urlRaw:"https://example.com/post",workDateRaw:"31/07/2026"};const missing=reconcileWorkSourceRows([base],{projectDomains:{}});assert.equal(missing.canonicalRows[0].isCountable,true);assert.deepEqual(missing.quarantinedRows,[]);assert.ok(missing.canonicalRows[0].issues.includes("project_settings_missing"));const conflict=reconcileWorkSourceRows([base],{projectDomains:{"Print Your Wear":{canonicalDomain:"another.example",includeSubdomains:false}}});assert.equal(conflict.canonicalRows[0].isCountable,true);assert.deepEqual(conflict.quarantinedRows,[]);assert.ok(conflict.canonicalRows[0].issues.includes("project_domain_conflict"));});
test("Slack item variants deduplicate and completed public URL wins",()=>{const values=[["Slack Item ID","Project","Member","Type","Status","URL","Date"],["S1","PrintYourWear","Lan","New Content","Review","https://app.bloggle.app/editor/1","2026-07-01"],["S1","Print Your Wear","Lan","New Content","Completed","https://example.com/live?utm_source=slack","2026-07-03"],["S1","Print Your Wear","Lan","New Content","Checked","https://example.com/review","2026-07-02"]];const result=reconcileWorkSourceRows(parseSlackListSheet(values));assert.equal(result.canonicalRows.length,1);assert.equal(result.duplicateRows.length,2);assert.equal(result.canonicalRows[0].canonicalUrl,"https://example.com/live");assert.equal(result.canonicalRows[0].project,"Print Your Wear");assert.equal(result.canonicalRows[0].isCountable,true);});
test("live Vietnamese Slack List headers and numeric Sheet dates are supported",()=>{const values=[["Ngày","Due Date","Task","Type","Dự án","Thực hiện","Desc/link","Trạng thái","Người Duyệt","Vấn đề/note","Slack Item ID"],[46202,"","Example","New Post","PrintYourWear","Thu Hằng","https://example.com/live","Completed","Reviewer","Updated","REC1"]];const rows=parseSlackListSheet(values);assert.equal(rows.length,1);assert.equal(rows[0].projectRaw,"PrintYourWear");assert.equal(rows[0].memberRaw,"Thu Hằng");assert.equal(rows[0].urlRaw,"https://example.com/live");const result=reconcileWorkSourceRows(rows);assert.equal(result.canonicalRows[0].workDate,"2026-06-29");assert.equal(result.canonicalRows[0].workType,"new_content");assert.equal(result.canonicalRows[0].isCountable,true);});
test("Checked, Hold, and unknown values never become payable",()=>{const base={source:"slack_list_sheet",sourceRowNumber:2,sourceItemId:"X",projectRaw:"Print Your Wear",memberRaw:"Lan",workTypeRaw:"Audit",urlRaw:"https://example.com/a",workDateRaw:"2026-07-01"};for(const status of ["Checked","Hold","Need Review"]){const row=reconcileWorkSourceRows([{...base,sourceStatusRaw:status}]).canonicalRows[0];assert.equal(row.isCountable,false,status);}});
test("Polynesian project aliases resolve to one canonical project",()=>{const base={source:"slack_list_sheet",sourceRowNumber:2,sourceItemId:"P1",projectRaw:"Polynesian Pride Blog",memberRaw:"Lan",workTypeRaw:"Audit",sourceStatusRaw:"Completed",urlRaw:"https://example.com/a",workDateRaw:"2026-07-01"};assert.equal(reconcileWorkSourceRows([base]).canonicalRows[0].project,"Stories of Polynesian Pride");});
