import { query } from "./db";

export const REQUIRED_TABLES = [
  "content_urls",
  "seo_performance_cache",
  "member_performance_cache",
  "refresh_runs",
  "sync_runs",
  "project_kpi_settings",
  "url_work_events",
  "monthly_member_kpi_targets",
  "kpi_work_unit_rules",
  "kpi_quality_criteria",
  "url_work_quality_reviews",
  "url_work_quality_scores",
  "member_month_quality_reviews",
  "projects",
  "project_aliases",
  "members",
  "member_aliases",
  "work_sync_runs",
  "work_source_rows",
  "content_url_aliases",
  "kpi_quality_rubrics",
  "kpi_quality_rubric_versions",
  "quality_review_calibrations",
  "gsc_fetch_runs",
  "gsc_url_daily_metrics",
  "performance_evaluation_cohorts",
  "performance_event_evaluations",
  "performance_project_member_month_results",
  "monthly_member_project_kpi_results",
  "monthly_kpi_component_definitions",
  "monthly_member_kpi_component_scores",
  "monthly_member_kpi_results",
  "kpi_override_audit_log",
  "project_domain_mappings",
  "project_settings_versions",
  "performance_range_results",
  "application_audit_log",
  "monthly_member_targets",
  "monthly_member_kpi_configs",
  "monthly_member_kpi_config_components",
];

export const REQUIRED_VIEWS = [
  "dashboard_url_performance",
  "dashboard_member_performance",
  "member_project_performance_final_view",
  "member_performance_final_view",
  "member_performance_summary",
];

export const PROJECT_KPI_SETTINGS_REQUIRED_COLUMNS = [
  "id",
  "project",
  "project_kpi_type",
  "project_start_date",
  "is_kpi_protection_enabled",
  "performance_floor_pct",
  "performance_cap_pct",
  "min_coverage_required",
  "min_eligible_urls",
  "max_excluded_no_data_rate",
  "allow_auto_floor_when_low_confidence",
  "allow_auto_floor_when_partial_coverage",
  "allow_auto_floor_when_high_no_data",
  "require_pm_review_below_pct",
  "pm_override_enabled",
  "pm_override_adjusted_pct",
  "pm_override_reason",
  "performance_weight_1m_pct",
  "performance_weight_3m_pct",
  "performance_weight_6m_pct",
  "performance_weight_all_time_pct",
  "normalize_missing_ranges",
  "enable_long_term_trend_protection",
  "trend_protection_floor_pct",
  "trend_protection_required_3m_pct",
  "trend_protection_required_all_time_pct",
  "not_enough_data_policy",
  "neutral_no_data_score_pct",
  "min_url_age_days_for_penalty",
  "max_no_data_penalty_pct",
  "no_data_rate_pm_review_pct",
  "enable_cohort_based_measurement",
  "url_work_date_field",
  "seo_lag_days",
  "cohort_mode_1m",
  "cohort_mode_3m",
  "cohort_mode_6m",
  "cohort_mode_all_time",
  "measurement_strategy",
  "performance_enabled_for_payroll",
  "min_project_age_days",
  "pre_window_days",
  "post_window_days",
  "min_eligible_events",
  "min_data_coverage_pct",
  "min_total_impressions",
  "zero_signal_score_pct",
  "new_signal_score_pct",
  "seasonality_mode",
  "control_adjustment_enabled",
  "performance_rule_version",
  "notes",
  "created_at",
  "updated_at",
];

export const REQUIRED_COLUMNS: Record<string, string[]> = {
  content_urls: [
    "id",
    "url_hash",
    "project_id",
    "project",
    "url",
    "normalized_domain",
    "classification_status",
    "classification_issues",
    "classification_version",
    "gsc_ready",
    "member_name",
    "member_email",
    "gsc_property",
    "is_active",
    "source",
    "unified_source_state",
    "first_seen_at",
    "last_seen_at",
    "content_worked_at",
    "content_type",
    "created_at",
    "updated_at",
  ],
  seo_performance_cache: [
    "id",
    "cache_key",
    "content_url_id",
    "url_hash",
    "project",
    "url",
    "member_name",
    "member_email",
    "gsc_property",
    "content_type",
    "range_key",
    "start_date",
    "end_date",
    "previous_start_date",
    "previous_end_date",
    "clicks",
    "impressions",
    "ctr",
    "position",
    "previous_clicks",
    "previous_impressions",
    "previous_ctr",
    "previous_position",
    "click_delta",
    "click_growth_pct",
    "impression_delta",
    "impression_growth_pct",
    "ctr_delta",
    "position_delta",
    "growth_status",
    "opportunity_status",
    "recommendation",
    "refreshed_at",
    "created_at",
    "updated_at",
  ],
  member_performance_cache: [
    "id",
    "cache_key",
    "project",
    "member_name",
    "member_email",
    "range_key",
    "start_date",
    "end_date",
    "previous_start_date",
    "previous_end_date",
    "url_count",
    "urls_with_data",
    "growing_urls",
    "stable_urls",
    "declining_urls",
    "no_data_urls",
    "clicks",
    "impressions",
    "ctr",
    "position",
    "previous_clicks",
    "previous_impressions",
    "click_delta",
    "click_growth_pct",
    "impression_delta",
    "impression_growth_pct",
    "quantity_index",
    "quality_index",
    "performance_kpi_pct",
    "impression_performance_score",
    "click_performance_score",
    "growth_coverage_score",
    "portfolio_health_score",
    "eligible_url_count",
    "excluded_no_data_url_count",
    "positive_url_count",
    "new_growth_url_count",
    "declining_url_count",
    "performance_kpi_status",
    "performance_confidence",
    "support_signal",
    "main_strength",
    "main_risk",
    "suggested_support",
    "refreshed_at",
    "created_at",
    "updated_at",
  ],
  refresh_runs: [
    "id",
    "status",
    "triggered_by",
    "range_key",
    "start_date",
    "end_date",
    "previous_start_date",
    "previous_end_date",
    "total_urls",
    "processed_urls",
    "urls_with_data",
    "no_data_urls",
    "failed_urls",
    "error_message",
    "started_at",
    "finished_at",
    "created_at",
    "updated_at",
  ],
  sync_runs: [
    "id",
    "source",
    "status",
    "total_rows",
    "inserted_rows",
    "updated_rows",
    "deactivated_rows",
    "failed_rows",
    "triggered_by",
    "error_message",
    "started_at",
    "finished_at",
    "created_at",
    "updated_at",
  ],
  project_kpi_settings: PROJECT_KPI_SETTINGS_REQUIRED_COLUMNS,
  url_work_events: [
    "id",
    "content_url_id",
    "project_id",
    "member_id",
    "project",
    "member_name",
    "member_email",
    "work_type",
    "work_date",
    "difficulty",
    "unit_value",
    "source",
    "source_row_key",
    "source_item_id",
    "source_status",
    "source_url",
    "canonical_url_snapshot",
    "completed_at",
    "date_confidence",
    "difficulty_source",
    "unit_rule_id",
    "unit_rule_version",
    "is_countable",
    "kpi_ready",
    "readiness_issues",
    "exclusion_reason",
    "approved_by",
    "approved_at",
    "status",
    "note",
    "source_lineage",
    "unified_source_state",
    "source_missing_at",
    "created_at",
    "updated_at",
  ],
  monthly_member_kpi_targets: [
    "id",
    "month_key",
    "project",
    "member_name",
    "member_email",
    "target_units",
    "target_urls",
    "quantity_weight_pct",
    "quality_weight_pct",
    "performance_weight_pct",
    "target_version",
    "base_target_units",
    "active_workday_ratio",
    "target_adjustment_reason",
    "is_locked",
    "locked_at",
    "locked_by",
    "notes",
    "created_at",
    "updated_at",
  ],
  kpi_work_unit_rules: [
    "id",
    "project",
    "member_name",
    "work_type",
    "difficulty",
    "unit_value",
    "is_active",
    "rule_version",
    "valid_from",
    "valid_to",
    "created_by",
    "notes",
    "created_at",
    "updated_at",
  ],
  kpi_quality_criteria: [
    "id",
    "project",
    "criterion_key",
    "criterion_name",
    "review_level",
    "weight_pct",
    "display_order",
    "is_active",
    "rubric_version_id",
    "work_type",
    "difficulty",
    "allows_na",
    "score_anchor_json",
    "description",
    "created_at",
    "updated_at",
  ],
  url_work_quality_reviews: [
    "id",
    "work_event_id",
    "review_status",
    "quality_pct",
    "rubric_version_id",
    "rubric_version_snapshot",
    "criteria_snapshot",
    "evidence",
    "override_reason",
    "admin_note",
    "reviewed_by",
    "reviewed_at",
    "created_at",
    "updated_at",
  ],
  url_work_quality_scores: [
    "id",
    "review_id",
    "criterion_id",
    "score",
    "is_na",
    "na_reason",
    "evidence",
    "criterion_key_snapshot",
    "criterion_name_snapshot",
    "weight_pct_snapshot",
    "note",
    "created_at",
    "updated_at",
  ],
  member_month_quality_reviews: [
    "id",
    "month_key",
    "project",
    "member_name",
    "member_email",
    "frequency_score",
    "collaboration_score",
    "review_status",
    "quality_pct",
    "admin_note",
    "reviewed_by",
    "reviewed_at",
    "created_at",
    "updated_at",
  ],
  projects: [
    "id",
    "canonical_name",
    "canonical_domain",
    "lifecycle",
    "gsc_property",
    "gsc_ready",
    "kpi_ready",
    "is_active",
    "created_at",
    "updated_at",
  ],
  project_aliases: [
    "id",
    "project_id",
    "alias",
    "alias_key",
    "is_active",
    "created_by",
    "created_at",
    "updated_at",
  ],
  members: [
    "id",
    "canonical_name",
    "email",
    "is_active",
    "created_at",
    "updated_at",
  ],
  member_aliases: [
    "id",
    "member_id",
    "alias",
    "alias_key",
    "is_active",
    "created_by",
    "created_at",
    "updated_at",
  ],
  work_sync_runs: [
    "id",
    "source",
    "status",
    "workflow_stage",
    "raw_row_count",
    "logical_item_count",
    "canonical_event_count",
    "accepted_row_count",
    "valid_work_record_count",
    "canonical_url_count",
    "new_event_count",
    "updated_event_count",
    "needs_attention_count",
    "committed_from_run_id",
    "idempotency_key",
    "quarantined_count",
    "duplicate_variant_count",
    "diagnostics",
    "triggered_by",
    "reviewed_by",
    "reviewed_at",
    "approval_reason",
    "error_message",
    "started_at",
    "finished_at",
    "created_at",
    "updated_at",
  ],
  work_source_rows: [
    "id",
    "sync_run_id",
    "source",
    "source_row_number",
    "source_item_id",
    "raw_payload",
    "normalized_payload",
    "logical_key",
    "is_canonical_variant",
    "is_quarantined",
    "quarantine_reasons",
    "ingested_at",
  ],
  content_url_aliases: [
    "id",
    "content_url_id",
    "alias_url",
    "alias_type",
    "is_active",
    "created_by",
    "created_at",
    "updated_at",
  ],
  kpi_quality_rubrics: [
    "id",
    "rubric_key",
    "name",
    "project",
    "work_type",
    "is_active",
    "created_at",
    "updated_at",
  ],
  kpi_quality_rubric_versions: [
    "id",
    "rubric_id",
    "version",
    "status",
    "total_weight_pct",
    "effective_from",
    "approved_by",
    "approved_at",
    "created_at",
  ],
  quality_review_calibrations: [
    "id",
    "work_event_id",
    "primary_review_id",
    "calibrator",
    "primary_quality_pct",
    "calibration_quality_pct",
    "difference_pct",
    "status",
    "note",
    "created_at",
    "updated_at",
  ],
  gsc_fetch_runs: [
    "id",
    "run_key",
    "status",
    "data_cutoff",
    "latest_complete_date",
    "properties_total",
    "properties_succeeded",
    "properties_failed",
    "diagnostics",
    "error_message",
    "started_at",
    "finished_at",
    "created_at",
    "updated_at",
  ],
  gsc_url_daily_metrics: [
    "id",
    "fetch_run_id",
    "gsc_property",
    "canonical_url",
    "metric_date",
    "search_type",
    "data_status",
    "clicks",
    "impressions",
    "ctr",
    "position",
    "error_code",
    "error_message",
    "created_at",
    "updated_at",
  ],
  performance_evaluation_cohorts: [
    "id",
    "month_key",
    "project",
    "member_name",
    "strategy",
    "cohort_key",
    "event_ids",
    "control_url_ids",
    "rule_version",
    "lineage",
    "created_at",
  ],
  performance_event_evaluations: [
    "id",
    "cohort_id",
    "work_event_id",
    "evaluation_key",
    "evaluation_horizon",
    "pre_start_date",
    "pre_end_date",
    "post_start_date",
    "post_end_date",
    "data_status",
    "comparison_coverage_pct",
    "raw_metrics",
    "sub_scores",
    "raw_pct",
    "payable_pct",
    "confidence",
    "status",
    "contamination_reason",
    "control_fallback_reason",
    "rule_version",
    "created_at",
    "updated_at",
  ],
  performance_project_member_month_results: [
    "id",
    "month_key",
    "project",
    "member_name",
    "cohort_id",
    "strategy",
    "raw_pct",
    "payable_pct",
    "coverage_pct",
    "comparison_coverage_pct",
    "confidence",
    "source_cohort",
    "rule_version",
    "override_reason",
    "status",
    "data_as_of",
    "sub_scores",
    "diagnostics",
    "calculated_at",
    "created_at",
    "updated_at",
  ],
  monthly_member_project_kpi_results: [
    "id",
    "month_key",
    "project",
    "member_name",
    "quantity_raw_pct",
    "quantity_payable_pct",
    "quantity_coverage_pct",
    "quality_raw_pct",
    "quality_payable_pct",
    "quality_coverage_pct",
    "seo_content_raw_pct",
    "seo_content_payable_pct",
    "performance_raw_pct",
    "performance_payable_pct",
    "performance_coverage_pct",
    "confidence",
    "source_cohort",
    "rule_version",
    "override_reason",
    "status",
    "source_ids",
    "diagnostics",
    "calculated_at",
    "created_at",
    "updated_at",
  ],
  monthly_kpi_component_definitions: [
    "id",
    "component_key",
    "version",
    "name",
    "default_weight_pct",
    "is_controllable",
    "is_required",
    "is_active",
    "created_at",
    "updated_at",
  ],
  monthly_member_kpi_component_scores: [
    "id",
    "month_key",
    "member_name",
    "component_key",
    "raw_pct",
    "payable_pct",
    "coverage_pct",
    "confidence",
    "source_cohort",
    "rule_version",
    "override_reason",
    "status",
    "reason",
    "source_ids",
    "audit_trail",
    "diagnostics",
    "is_not_applicable",
    "na_reason",
    "evidence",
    "data_as_of",
    "calculated_at",
    "approved_by",
    "approved_at",
    "created_at",
    "updated_at",
  ],
  monthly_member_kpi_results: [
    "id",
    "month_key",
    "member_name",
    "version",
    "raw_pct",
    "payable_pct",
    "coverage_pct",
    "confidence",
    "source_cohort",
    "rule_version",
    "override_reason",
    "status",
    "payout_base_vnd",
    "payout_vnd",
    "source_ids",
    "audit_trail",
    "snapshot_payload",
    "calculated_at",
    "approved_by",
    "approved_at",
    "locked_by",
    "locked_at",
    "reopened_from_id",
    "created_at",
    "updated_at",
  ],
  kpi_override_audit_log: [
    "id",
    "month_key",
    "member_name",
    "project",
    "component_key",
    "entity_type",
    "entity_id",
    "before_value",
    "after_value",
    "reason",
    "actor",
    "action",
    "created_at",
  ],
  project_domain_mappings: [
    "id",
    "project_id",
    "normalized_domain",
    "mapping_version",
    "effective_from",
    "effective_to",
    "status",
    "reason",
    "created_by",
    "approved_by",
    "approved_at",
    "created_at",
    "updated_at",
  ],
  project_settings_versions: [
    "id",
    "project_id",
    "version",
    "effective_from",
    "effective_to",
    "status",
    "lifecycle",
    "canonical_domain",
    "gsc_property",
    "gsc_ready",
    "kpi_ready",
    "performance_weight_3m_pct",
    "performance_weight_6m_pct",
    "performance_weight_all_time_pct",
    "settings_payload",
    "reason",
    "created_by",
    "approved_by",
    "approved_at",
    "created_at",
    "updated_at",
  ],
  performance_range_results: [
    "id",
    "as_of_month",
    "project_id",
    "member_id",
    "range_key",
    "impression_performance_pct",
    "click_performance_pct",
    "growth_coverage_pct",
    "portfolio_health_pct",
    "raw_pct",
    "payable_pct",
    "coverage_pct",
    "confidence",
    "status",
    "source_cohort",
    "source_ids",
    "diagnostics",
    "rule_version",
    "data_as_of",
    "calculated_at",
    "created_at",
    "updated_at",
  ],
  monthly_member_targets: [
    "id",
    "month_key",
    "member_id",
    "member_name",
    "member_email",
    "target_units",
    "base_target_units",
    "active_workday_ratio",
    "adjustment_reason",
    "notes",
    "version",
    "status",
    "created_by",
    "approved_by",
    "approved_at",
    "locked_at",
    "locked_by",
    "created_at",
    "updated_at",
  ],
  monthly_member_kpi_configs: [
    "id",
    "month_key",
    "member_id",
    "member_name",
    "version",
    "status",
    "social_video_enabled",
    "reason",
    "created_by",
    "approved_by",
    "approved_at",
    "locked_at",
    "locked_by",
    "reopened_from_id",
    "created_at",
    "updated_at",
  ],
  monthly_member_kpi_config_components: [
    "id",
    "config_id",
    "component_key",
    "weight_pct",
    "is_required",
    "allows_na",
    "display_order",
    "created_at",
  ],
  application_audit_log: [
    "id",
    "actor",
    "action",
    "entity_type",
    "entity_id",
    "before_value",
    "after_value",
    "reason",
    "request_id",
    "created_at",
  ],
};

export type DbSchemaHealth = {
  ok: boolean;
  missingTables: string[];
  missingViews: string[];
  missingColumns: string[];
  missing: string[];
  migrationWarnings: string[];
  projectKpiSettings: ProjectKpiSettingsDiagnostic;
};
export type ProjectKpiSettingsDiagnostic = {
  current_database: string | null;
  current_schema: string | null;
  current_user: string | null;
  project_kpi_settings_exists: boolean;
  project_kpi_settings_schema: string | null;
  missing_project_kpi_columns: string[];
  raw_error_code: string | null;
  raw_error_message: string | null;
};

const clean = (message: unknown) =>
  String(message || "").replace(
    /postgres(?:ql)?:\/\/[^\s]+/gi,
    "[redacted database url]",
  );

export function getDbErrorCode(error: unknown) {
  return (error as { code?: string } | null)?.code || null;
}

export function getDbErrorMessage(error: unknown) {
  return error instanceof Error ? clean(error.message) : clean(error);
}

export async function getProjectKpiSettingsDiagnostic(
  error?: unknown,
): Promise<ProjectKpiSettingsDiagnostic> {
  const base: ProjectKpiSettingsDiagnostic = {
    current_database: null,
    current_schema: null,
    current_user: null,
    project_kpi_settings_exists: false,
    project_kpi_settings_schema: null,
    missing_project_kpi_columns: [],
    raw_error_code: error ? getDbErrorCode(error) : null,
    raw_error_message: error ? getDbErrorMessage(error) : null,
  };
  try {
    const [identity, table, columns] = await Promise.all([
      query<{
        current_database: string;
        current_schema: string;
        current_user: string;
      }>(`select current_database(), current_schema(), current_user`),
      query<{ table_schema: string; table_type: string }>(
        `select table_schema, table_type from information_schema.tables where table_schema='public' and table_name='project_kpi_settings' limit 1`,
      ),
      query<{ column_name: string }>(
        `select column_name from information_schema.columns where table_schema='public' and table_name='project_kpi_settings'`,
      ),
    ]);
    const foundColumns = new Set(columns.rows.map((row) => row.column_name));
    return {
      ...base,
      ...identity.rows[0],
      project_kpi_settings_exists: table.rows.length > 0,
      project_kpi_settings_schema: table.rows[0]?.table_schema || null,
      missing_project_kpi_columns: PROJECT_KPI_SETTINGS_REQUIRED_COLUMNS.filter(
        (column) => !foundColumns.has(column),
      ),
    };
  } catch (diagnosticError) {
    return {
      ...base,
      raw_error_code: getDbErrorCode(diagnosticError) || base.raw_error_code,
      raw_error_message:
        getDbErrorMessage(diagnosticError) || base.raw_error_message,
    };
  }
}

export async function checkDbSchemaHealth(): Promise<DbSchemaHealth> {
  const [relations, columns, projectKpiSettings] = await Promise.all([
    query<{ table_name: string; table_type: string }>(
      `select table_name, table_type from information_schema.tables where table_schema='public' and table_name = any($1::text[])`,
      [[...REQUIRED_TABLES, ...REQUIRED_VIEWS]],
    ),
    query<{ table_name: string; column_name: string }>(
      `select table_name, column_name from information_schema.columns where table_schema='public' and table_name = any($1::text[])`,
      [Object.keys(REQUIRED_COLUMNS)],
    ),
    getProjectKpiSettingsDiagnostic(),
  ]);
  const relationMap = new Map(
    relations.rows.map((row) => [row.table_name, row.table_type]),
  );
  const columnMap = columns.rows.reduce<Record<string, Set<string>>>(
    (acc, row) => {
      (acc[row.table_name] ??= new Set()).add(row.column_name);
      return acc;
    },
    {},
  );
  const missingTables = REQUIRED_TABLES.filter(
    (name) => !relationMap.has(name),
  );
  const missingViews = REQUIRED_VIEWS.filter((name) => !relationMap.has(name));
  const missingColumns = Object.entries(REQUIRED_COLUMNS).flatMap(
    ([table, required]) =>
      required
        .filter((column) => !columnMap[table]?.has(column))
        .map((column) => `${table}.${column}`),
  );
  const missing = [
    ...missingTables.map((name) => `table:${name}`),
    ...missingViews.map((name) => `view:${name}`),
    ...missingColumns,
  ];
  const migrationWarnings = [
    missingViews.includes("member_project_performance_final_view") ||
    missingColumns.includes("member_performance_cache.project")
      ? "Project-aware performance schema is missing. Run migrations/20260710_member_project_performance.sql in Neon."
      : null,
    missingTables.includes("url_work_events") ||
    missingColumns.some((column) => column.startsWith("url_work_events."))
      ? "Work-event schema is missing. Run migrations/20260710_url_work_events.sql in Neon."
      : null,
    [
      "monthly_member_kpi_targets",
      "kpi_work_unit_rules",
      "kpi_quality_criteria",
      "url_work_quality_reviews",
      "url_work_quality_scores",
      "member_month_quality_reviews",
    ].some((table) => missingTables.includes(table)) ||
    missingColumns.some((column) =>
      [
        "monthly_member_kpi_targets.",
        "kpi_work_unit_rules.",
        "kpi_quality_criteria.",
        "url_work_quality_reviews.",
        "url_work_quality_scores.",
        "member_month_quality_reviews.",
      ].some((prefix) => column.startsWith(prefix)),
    )
      ? "Monthly KPI schema is missing or incomplete. Run migrations/20260710_monthly_kpi.sql in Neon."
      : null,
    [
      "work_source_rows",
      "gsc_url_daily_metrics",
      "monthly_member_project_kpi_results",
      "monthly_member_kpi_results",
    ].some((table) => missingTables.includes(table)) ||
    missingColumns.some(
      (column) =>
        column.startsWith("url_work_events.source_item_id") ||
        column.startsWith("project_kpi_settings.measurement_strategy"),
    )
      ? "Monthly KPI Engine v2 is missing or incomplete. Run migrations/20260714_monthly_kpi_engine_v2.sql on staging only."
      : null,
    [
      "project_settings_versions",
      "performance_range_results",
      "application_audit_log",
    ].some((table) => missingTables.includes(table)) ||
    missingColumns.some(
      (column) =>
        column.startsWith("content_urls.classification_") ||
        column.startsWith("url_work_events.kpi_ready"),
    )
      ? "Unified application schema is missing or incomplete. Run migrations/20260715_unified_application.sql on staging only."
      : null,
    [
      "monthly_member_targets",
      "monthly_member_kpi_configs",
      "monthly_member_kpi_config_components",
    ].some((table) => missingTables.includes(table)) ||
    missingColumns.some(
      (column) =>
        column.startsWith("url_work_events.source_lineage") ||
        column.startsWith("work_sync_runs.idempotency_key"),
    )
      ? "Unified remediation schema is missing or incomplete. Run migrations/20260715_unified_remediation.sql on Preview/staging only."
      : null,
  ].filter((message): message is string => Boolean(message));
  return {
    ok: missing.length === 0,
    missingTables,
    missingViews,
    missingColumns,
    missing,
    migrationWarnings,
    projectKpiSettings,
  };
}
